import { useState } from 'react'
import styles from './ReportPanel.module.css'

function parseReport(text) {
  const sections = []
  const lines = text.split('\n')
  let current = null

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (current) sections.push(current)
      current = { heading: line.replace('## ', '').trim(), body: [] }
    } else if (current) { 
      if (line.trim()) current.body.push(line.trim())
    }
  }
  if (current) sections.push(current)
  return sections
}

export default function ReportPanel({ onClose }) {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  const generate = async () => {
    setLoading(true)
    setError(null)
    setReport(null)
    try {
      const res = await fetch('/api/report/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scenario: 'baseline' }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.detail || 'Generation failed')
      setReport(data.report)
    } catch (e) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  const sections = report ? parseReport(report) : []

  return (
    <div className={styles.overlay} onClick={e => e.target === e.currentTarget && onClose()}>
      <div className={styles.modal}>

        <div className={styles.modalHead}>
          <div className={styles.modalTitle}>
            <span className={styles.titleIcon}>📋</span>
            <div>
              <h2 className={styles.titleText}>AI Conservation Report</h2>
              <p className={styles.titleSub}>Generated from 20-year AETHERA cascade simulation · Sundarbans</p>
            </div>
          </div>
          <button className={styles.closeBtn} onClick={onClose}>✕</button>
        </div>

        <div className={styles.modalBody}>
          {!report && !loading && !error && (
            <div className={styles.promptState}>
              <div className={styles.promptIcon}>🌿</div>
              <h3 className={styles.promptTitle}>Generate Ecological Assessment</h3>
              <p className={styles.promptDesc}>
                AETHERA will analyse all 20 years of simulation data — flood risk, glacier melt,
                animal migration patterns, and zoonotic exposure — and produce a structured
                scientific report with conservation recommendations.
              </p>
              <button className={styles.generateBtn} onClick={generate}>
                Generate Report
              </button>
            </div>
          )}

          {loading && (
            <div className={styles.loadingState}>
              <div className={styles.loadSpinner} />
              <p className={styles.loadText}>Analysing 20 years of cascade data…</p>
              <p className={styles.loadSub}>This takes 10–20 seconds</p>
            </div>
          )}

          {error && (
            <div className={styles.errorState}>
              <span className={styles.errorIcon}>⚠</span>
              <p className={styles.errorMsg}>{error}</p>
              {error.includes('API key') && (
                <div className={styles.errorHint}>
                  <p>Open <code>C:\aethera\backend\.env</code> and set:</p>
                  <code className={styles.codeBlock}>ANTHROPIC_API_KEY=sk-ant-…your key…</code>
                  <p>Get a free key at <strong>console.anthropic.com</strong></p>
                </div>
              )}
              <button className={styles.retryBtn} onClick={generate}>Try Again</button>
            </div>
          )}

          {sections.length > 0 && (
            <div className={styles.report}>
              {sections.map((s, i) => (
                <div key={i} className={styles.section}>
                  <h3 className={styles.sectionHead}>{s.heading}</h3>
                  <div className={styles.sectionBody}>
                    {s.body.map((para, j) => (
                      <p key={j} className={styles.para}>{para}</p>
                    ))}
                  </div>
                </div>
              ))}
              <div className={styles.reportFoot}>
                <span>Generated by Claude · AETHERA v2.0 · Baseline scenario · Synthetic data</span>
                <button className={styles.regenBtn} onClick={generate}>↻ Regenerate</button>
              </div>
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
