"""initial_schema

Revision ID: eb0bbbe07121
Revises: 
Create Date: 2026-02-22 02:31:18.873189

"""
from alembic import op
import sqlalchemy as sa


revision = 'eb0bbbe07121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('glacier_contribution_cm', sa.Float(), nullable=True),
    sa.Column('sea_level_rise_mm', sa.Float(), nullable=True),
    sa.Column('salinity_proxy', sa.Float(), nullable=True),
    sa.Column('vegetation_proxy', sa.Float(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_data_id'), 'climate_data', ['id'], unique=False)
    op.create_index(op.f('ix_climate_data_year'), 'climate_data', ['year'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('flood_risk', sa.Float(), nullable=False),
    sa.Column('glacier_amplification', sa.Float(), nullable=False),
    sa.Column('prey_stress_index', sa.Float(), nullable=False),
    sa.Column('prey_migration_probability', sa.Float(), nullable=False),
    sa.Column('tiger_migration_probability', sa.Float(), nullable=False),
    sa.Column('zoonotic_risk_index', sa.Float(), nullable=False),
    sa.Column('human_density_factor', sa.Float(), nullable=True),
    sa.Column('wildlife_displacement_score', sa.Float(), nullable=True),
    sa.Column('is_projection', sa.Boolean(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_id'), 'simulation_results', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_results_year'), 'simulation_results', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_results_year'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_climate_data_year'), table_name='climate_data')
    op.drop_index(op.f('ix_climate_data_id'), table_name='climate_data')
    op.drop_table('climate_data')
    # ### end Alembic commands ###
